### ISSUE TITLE
Criar e responder 4 perguntas de negócio

### ISSUE THREAD

**Issue by ojulianos** [ojulianos/banco_2_seguros_imoveis#10]
Criar e responder 4 perguntas de negócio. Publicar no GitHub (Manter/mostrar histórico das alterações).

**Comment by ojulianos** [comment]
@Anderson-Pizzolo você precisa testar as consultas das perguntas que me mandou, algumas delas estão no formato pra o MySQL não SQL Server.

**Comment by Anderson-Pizzolo** [comment]
blz vou dar uma olhada agora
