### ISSUE TITLE
Escrever dicionário de dados

### ISSUE THREAD

**Issue by ojulianos** [ojulianos/banco_2_seguros_imoveis#9]
Documentar o dicionário de dados do seu modelo físico de acordo com o template 1 (modelo disponível no AVA). Publicar no GitHub (Manter/mostrar histórico das alterações).

**Comment by jzpacheco** [comment]
Dicionário criado com informações básicas como nome da coluna, descrição, chave pk, fk. Ainda falta adicionar informações referentes aos indíces, tamanho mínimo e máximo do campo. 
Também necessário revisar e complementar informações de nulidade da coluna.

Para facilitar e organizar o projeto, para as partes faltantes será criado issues correspondentes.
